name: Simple CI/CD Workflow

"on":
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: repository
        uses: actions/checkout@v4

      - name: Build step
        run: echo "Build OK - HTML validated"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy step
        run: echo "Deployment successful to staging"

  upload-artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload index.html as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: webpage
          path: index.html
